### PR TITLE
Dockerfile

### PR DESCRIPTION
**Pull request by zscole**
Builds without UI

### CODE REVIEW

**Comment by zscole** [comment]
Yeah, I can add that, but I should note that I built this intentionally from the branch for CPU mining for testing purposes.

**Comment by illera88** [comment]
if you build it with GPU capabilities you will have the option to do both CPU and GPU

Cheers

**Comment by zscole** [comment]
Ah, ok. I'll make the change, test it out, and push it.

**Comment by huglester** [comment]
you are cloning probably wrong repo in this commit

**Comment by zscole** [comment]
We're cloning the correct repo, but this Dockerfile was put together for specific testing purposes according to some instruction from @BigRomanov. We're going to be pushing an updated version soon though since some changes have been made since.

**Comment by Webonnix** [comment]
Hi
We appreciate your support in improving the project.

About the request:
1) Dockerfile has a link to your repository
2) The final image has a large layer,which increases the size:
 - original image = 88.9 MB
 - final image = 1.46 GB

Unfortunately, we cannot accept your request
Thanks for understanding

**Pull request closed without merging**
