### PR TITLE
Add Dockerfile.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by monaka-hashhub** [comment]
FYI. The HashHub dev team started to publish Docker image. https://hub.docker.com/r/hashhub/beam

**Comment by Webonnix** [comment]
Hi
We appreciate your support in improving the project.
About the request:
1) The image has a layer,which increases the size:
 - original image = 88.9 MB
 - final image = 824 MB
You created a good solution,but needs image with less size.
Unfortunately,we cannot accept your request
Thanks for understanding

**Comment by Webonnix** [comment]
Hi
We appreciate your support in improving the project.
About the request:
The image has a layer,which increases the size:
- original image = 88.9 MB
- final image = 824 MB
You created a good solution,but needs image with less size.
Unfortunately,we cannot accept your request
Thanks for understanding

**Comment by Webonnix** [comment]
Hi
We appreciate your support in improving the project.
About the request:

    The image has a layer,which increases the size:

    original image = 88.9 MB
    final image = 824 MB
    You created a good solution,but needs image with less size.
    Unfortunately,we cannot accept your request
    Thanks for understanding

**Comment by Webonnix** [comment]
Hi
We appreciate your support in improving the project.
About the request:
The image has a layer,which increases the size:
original image = 88.9 MB
final image = 824 MB
You created a good solution,but needs image with less size.
Unfortunately,we cannot accept your request
Thanks for understanding

**Pull request closed without merging**
